### ISSUE TITLE
Sprint 3: New BQ formulation and implementation in Kotlin

### ISSUE THREAD

**Issue by Juanchix** [ISIS3510-MOBILE-T34/SpendiQ_Android#22]

**Comment by Juanchix** [comment]
After reviewing some features and data used in the app, I decided to create a new BQ type 2 and 3

**Comment by J0FR** [comment]
The new business questions (Type 2 and Type 3) have been successfully formulated and implemented in Kotlin. After reviewing the app's features and data, these new questions were defined to enhance the application's functionality. Since everything is in order and meets the sprint requirements, I am proceeding to close this issue.

Great job @Juanchix on this update!
